apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db-service.fullname" . }}-secret
  labels:
    app: {{ include "db-service.name" . }}
type: Opaque
data:
  db-user: {{ .Values.db.user | b64enc }}
  db-password: {{ .Values.db.password | b64enc }}
  db-database: {{ .Values.db.database | b64enc }}
